language: cpp
sudo: required
dist: xenial

os:
    - linux
    
compiler:
  - clang
  - gcc

install:
    - sudo apt-get install git unzip build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev libevent-dev autogen automake libtool libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools qt5-default
    
script:
    - git clone https://github.com/carsenk/denarius
    - cd denarius
    - sed -i 's/c99/gnu99/' ~/denarius/denarius-qt.pro
    - qmake "USE_QRCODE=1" "USE_UPNP=1" denarius-qt.pro 
    - make
    - make check
    - cp Denarius /usr/bin/Denarius

    
branches:
    only:
- master
